"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-07-13 22:39:36.411286
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('knowledge_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('chapter', sa.String(length=100), nullable=False),
    sa.Column('dimension', sa.Enum('STATISTICS_FOUNDATION', 'LINEAR_MODELS', 'SELECTION_REGULARIZATION', 'CLASSIFICATION', 'EVALUATION_ENSEMBLE', name='abilitydimension', native_enum=False, length=40), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('resource_url', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('difficulty BETWEEN 1 AND 5', name='ck_knowledge_difficulty'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_knowledge_points_chapter'), 'knowledge_points', ['chapter'], unique=False)
    op.create_index(op.f('ix_knowledge_points_code'), 'knowledge_points', ['code'], unique=True)
    op.create_index(op.f('ix_knowledge_points_dimension'), 'knowledge_points', ['dimension'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'TEACHER', 'ADMIN', name='role', native_enum=False, length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('classrooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grade_id', 'name', name='uq_classroom_grade_name')
    )
    op.create_index(op.f('ix_classrooms_grade_id'), 'classrooms', ['grade_id'], unique=False)
    op.create_table('prerequisites',
    sa.Column('knowledge_point_id', sa.Integer(), nullable=False),
    sa.Column('prerequisite_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('knowledge_point_id <> prerequisite_id', name='ck_prerequisite_not_self'),
    sa.ForeignKeyConstraint(['knowledge_point_id'], ['knowledge_points.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prerequisite_id'], ['knowledge_points.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('knowledge_point_id', 'prerequisite_id')
    )
    op.create_table('recommendation_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diagnostic_algorithm', sa.Enum('RULE', 'BKT', name='masteryalgorithm', native_enum=False, length=20), nullable=False),
    sa.Column('min_path_length', sa.Integer(), nullable=False),
    sa.Column('max_path_length', sa.Integer(), nullable=False),
    sa.Column('mastery_threshold', sa.Float(), nullable=False),
    sa.Column('weak_threshold', sa.Float(), nullable=False),
    sa.Column('weak_priority_weight', sa.Float(), nullable=False),
    sa.Column('mastered_alignment_weight', sa.Float(), nullable=False),
    sa.Column('length_penalty_weight', sa.Float(), nullable=False),
    sa.Column('difficulty_jump_weight', sa.Float(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('mastery_threshold BETWEEN 0 AND 1', name='ck_config_mastery_threshold'),
    sa.CheckConstraint('max_path_length >= min_path_length', name='ck_config_length_order'),
    sa.CheckConstraint('min_path_length >= 1', name='ck_config_min_length'),
    sa.CheckConstraint('weak_threshold BETWEEN 0 AND 1', name='ck_config_weak_threshold'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('student_no', sa.String(length=30), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_profiles_classroom_id'), 'student_profiles', ['classroom_id'], unique=False)
    op.create_index(op.f('ix_student_profiles_student_no'), 'student_profiles', ['student_no'], unique=True)
    op.create_index(op.f('ix_student_profiles_user_id'), 'student_profiles', ['user_id'], unique=True)
    op.create_table('teacher_classes',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('teacher_id', 'classroom_id')
    )
    op.create_table('exercise_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_point_id', sa.Integer(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_point_id'], ['knowledge_points.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_attempts_attempted_at'), 'exercise_attempts', ['attempted_at'], unique=False)
    op.create_index(op.f('ix_exercise_attempts_knowledge_point_id'), 'exercise_attempts', ['knowledge_point_id'], unique=False)
    op.create_index(op.f('ix_exercise_attempts_student_id'), 'exercise_attempts', ['student_id'], unique=False)
    op.create_table('knowledge_visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_point_id', sa.Integer(), nullable=False),
    sa.Column('visited_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.CheckConstraint('duration_seconds >= 0', name='ck_visit_duration'),
    sa.ForeignKeyConstraint(['knowledge_point_id'], ['knowledge_points.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_visits_knowledge_point_id'), 'knowledge_visits', ['knowledge_point_id'], unique=False)
    op.create_index(op.f('ix_knowledge_visits_student_id'), 'knowledge_visits', ['student_id'], unique=False)
    op.create_index(op.f('ix_knowledge_visits_visited_at'), 'knowledge_visits', ['visited_at'], unique=False)
    op.create_table('latent_mastery',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_point_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.CheckConstraint('score BETWEEN 0 AND 1', name='ck_latent_score'),
    sa.ForeignKeyConstraint(['knowledge_point_id'], ['knowledge_points.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id', 'knowledge_point_id')
    )
    op.create_table('learning_paths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('target_knowledge_point_id', sa.Integer(), nullable=False),
    sa.Column('algorithm', sa.Enum('RULE', 'BKT', name='masteryalgorithm', native_enum=False, length=20), nullable=False),
    sa.Column('state', sa.Enum('CURRENT', 'STALE', name='pathstate', native_enum=False, length=20), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('length_exception', sa.String(length=100), nullable=True),
    sa.Column('config_snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_knowledge_point_id'], ['knowledge_points.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_paths_state'), 'learning_paths', ['state'], unique=False)
    op.create_index(op.f('ix_learning_paths_student_id'), 'learning_paths', ['student_id'], unique=False)
    op.create_index(op.f('ix_learning_paths_target_knowledge_point_id'), 'learning_paths', ['target_knowledge_point_id'], unique=False)
    op.create_index('ix_path_student_state', 'learning_paths', ['student_id', 'state'], unique=False)
    op.create_table('mastery_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_point_id', sa.Integer(), nullable=False),
    sa.Column('algorithm', sa.Enum('RULE', 'BKT', name='masteryalgorithm', native_enum=False, length=20), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('UNKNOWN', 'WEAK', 'LEARNING', 'MASTERED', name='masterystatus', native_enum=False, length=20), nullable=False),
    sa.Column('evidence_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('score BETWEEN 0 AND 1', name='ck_mastery_score'),
    sa.ForeignKeyConstraint(['knowledge_point_id'], ['knowledge_points.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'knowledge_point_id', 'algorithm', name='uq_mastery_student_knowledge_algorithm')
    )
    op.create_index('ix_mastery_algorithm_status', 'mastery_results', ['algorithm', 'status'], unique=False)
    op.create_index(op.f('ix_mastery_results_knowledge_point_id'), 'mastery_results', ['knowledge_point_id'], unique=False)
    op.create_index(op.f('ix_mastery_results_status'), 'mastery_results', ['status'], unique=False)
    op.create_index(op.f('ix_mastery_results_student_id'), 'mastery_results', ['student_id'], unique=False)
    op.create_table('video_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_point_id', sa.Integer(), nullable=False),
    sa.Column('progress_percent', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('progress_percent BETWEEN 0 AND 100', name='ck_video_progress'),
    sa.ForeignKeyConstraint(['knowledge_point_id'], ['knowledge_points.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'knowledge_point_id', name='uq_video_student_knowledge')
    )
    op.create_index(op.f('ix_video_progress_knowledge_point_id'), 'video_progress', ['knowledge_point_id'], unique=False)
    op.create_index(op.f('ix_video_progress_student_id'), 'video_progress', ['student_id'], unique=False)
    op.create_table('learning_path_items',
    sa.Column('path_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('knowledge_point_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('MASTERED', 'RECOMMENDED', 'TARGET', name='pathnodestatus', native_enum=False, length=20), nullable=False),
    sa.Column('mastery_score', sa.Float(), nullable=False),
    sa.CheckConstraint('mastery_score BETWEEN 0 AND 1', name='ck_path_item_mastery'),
    sa.ForeignKeyConstraint(['knowledge_point_id'], ['knowledge_points.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['path_id'], ['learning_paths.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('path_id', 'sequence'),
    sa.UniqueConstraint('path_id', 'knowledge_point_id', name='uq_path_knowledge_point')
    )
    op.create_index(op.f('ix_learning_path_items_knowledge_point_id'), 'learning_path_items', ['knowledge_point_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learning_path_items_knowledge_point_id'), table_name='learning_path_items')
    op.drop_table('learning_path_items')
    op.drop_index(op.f('ix_video_progress_student_id'), table_name='video_progress')
    op.drop_index(op.f('ix_video_progress_knowledge_point_id'), table_name='video_progress')
    op.drop_table('video_progress')
    op.drop_index(op.f('ix_mastery_results_student_id'), table_name='mastery_results')
    op.drop_index(op.f('ix_mastery_results_status'), table_name='mastery_results')
    op.drop_index(op.f('ix_mastery_results_knowledge_point_id'), table_name='mastery_results')
    op.drop_index('ix_mastery_algorithm_status', table_name='mastery_results')
    op.drop_table('mastery_results')
    op.drop_index('ix_path_student_state', table_name='learning_paths')
    op.drop_index(op.f('ix_learning_paths_target_knowledge_point_id'), table_name='learning_paths')
    op.drop_index(op.f('ix_learning_paths_student_id'), table_name='learning_paths')
    op.drop_index(op.f('ix_learning_paths_state'), table_name='learning_paths')
    op.drop_table('learning_paths')
    op.drop_table('latent_mastery')
    op.drop_index(op.f('ix_knowledge_visits_visited_at'), table_name='knowledge_visits')
    op.drop_index(op.f('ix_knowledge_visits_student_id'), table_name='knowledge_visits')
    op.drop_index(op.f('ix_knowledge_visits_knowledge_point_id'), table_name='knowledge_visits')
    op.drop_table('knowledge_visits')
    op.drop_index(op.f('ix_exercise_attempts_student_id'), table_name='exercise_attempts')
    op.drop_index(op.f('ix_exercise_attempts_knowledge_point_id'), table_name='exercise_attempts')
    op.drop_index(op.f('ix_exercise_attempts_attempted_at'), table_name='exercise_attempts')
    op.drop_table('exercise_attempts')
    op.drop_table('teacher_classes')
    op.drop_index(op.f('ix_student_profiles_user_id'), table_name='student_profiles')
    op.drop_index(op.f('ix_student_profiles_student_no'), table_name='student_profiles')
    op.drop_index(op.f('ix_student_profiles_classroom_id'), table_name='student_profiles')
    op.drop_table('student_profiles')
    op.drop_table('recommendation_configs')
    op.drop_table('prerequisites')
    op.drop_index(op.f('ix_classrooms_grade_id'), table_name='classrooms')
    op.drop_table('classrooms')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_knowledge_points_dimension'), table_name='knowledge_points')
    op.drop_index(op.f('ix_knowledge_points_code'), table_name='knowledge_points')
    op.drop_index(op.f('ix_knowledge_points_chapter'), table_name='knowledge_points')
    op.drop_table('knowledge_points')
    op.drop_table('grades')
    # ### end Alembic commands ###

